notifications:
  email: false
language: node_js
node_js:
  - node
sudo: required
#services:
#  - docker
before_install:
  - ci/install.sh
script:
  - source emsdk/emsdk_env.sh && ./build.sh && ci/post-build.sh
#deploy:
#  - provider: bintray
#    on:
#      all_branches: true
#    file: bintray.json
#    user: antelle
#    key:
#      secure: NOjw/LmCCFkELtHyHeQof5mqHEo2uiKs2WdcOdFodoxvY1oUXJoJJkhZWuIGQAV3FwZ3Qtwx2aB+nRacYwVzfUI/m/v7rvMUyoLpQYM5uikSj6LYdx7sqAoT0gonsKHAzpin2itD3M3h0aJe5RtKg8NifvTIyUFQDkTJQvWb9YQmkaoAcoI+AgCr6MS/04kyoHQQIQ5qxn0FJKKMIeC9ARcFVzO1XzPRm06h3tupbhcXHpTjUjd00zhfpQJI2MmWcgfY6ovXhHD3gC7eVenyknKlqPsFtBMKUT2Mrde3lGSkeYwaygTvAeO1elFNAKxDQkoipvunyNNg41nkuALlSbVl/DOPO+QaSAJRJkp2kzuVVe5GCC7VfKBiszths2y2Uye4mpQ0OP0NPuYCgCCatBIfxcxYCvnqs3qupZgZjtAEUEcMPauOF2lWsgzA2+uTDKPy0APLyiDP5/TcjlKOM7NPIbvf1bvqNak5e+MlK1RSjgWfTkM8ABWgTPhF7tG9WYWhGK0l+A9aN6OJM+osmFJYESqm7wIb41aEEn7RX8LDVMGzZ6Axvg4iRSevQuiNWYUMhrCfrf6Uxx4UqB5Fith9MNkllfsTc6YXjlfBHGQ2CWHfMIjow//ZBbW4N0FL6vhw46IID55IlwrB0/WOYVtmzYkLWlnoTZeVeFcjpso=
#    skip_cleanup: true
